package server
import("encoding/json";"fmt";"net/http";"strconv";"strings";"github.com/stockyard-dev/stockyard-pasture/internal/store")
func(s *Server)handleListEnvironments(w http.ResponseWriter,r *http.Request){list,_:=s.db.ListEnvironments();if list==nil{list=[]store.Environment{}};writeJSON(w,200,list)}
func(s *Server)handleCreateEnvironment(w http.ResponseWriter,r *http.Request){var e store.Environment;json.NewDecoder(r.Body).Decode(&e);if e.Name==""{writeError(w,400,"name required");return};if err:=s.db.CreateEnvironment(&e);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,e)}
func(s *Server)handleDeleteEnvironment(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteEnvironment(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleListVars(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);list,_:=s.db.ListVars(id);if list==nil{list=[]store.EnvVar{}};writeJSON(w,200,list)}
func(s *Server)handleSetVar(w http.ResponseWriter,r *http.Request){envID,_:=strconv.ParseInt(r.PathValue("id"),10,64);var v store.EnvVar;json.NewDecoder(r.Body).Decode(&v);v.EnvID=envID;if v.Key==""{writeError(w,400,"key required");return};if err:=s.db.SetVar(&v);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,200,map[string]string{"status":"set"})}
func(s *Server)handleDeleteVar(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteVar(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleExport(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);vars,_:=s.db.ExportVars(id);var sb strings.Builder;for _,v:=range vars{sb.WriteString(fmt.Sprintf("%s=%s\n",v.Key,v.Value))};w.Header().Set("Content-Type","text/plain");w.Header().Set("Content-Disposition",fmt.Sprintf("attachment; filename=env-%d.env",id));w.Write([]byte(sb.String()))}
func(s *Server)handleStats(w http.ResponseWriter,r *http.Request){n,_:=s.db.CountVars();writeJSON(w,200,map[string]interface{}{"vars":n})}
