package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pasture</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--blue:#4a7ec4;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.btn-s{border-color:var(--green);color:var(--green)}.btn-s:hover{background:var(--green);color:var(--bg)}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:.5rem;align-items:center}.toolbar select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.post{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem}.post-title{font-size:.82rem;font-weight:600;display:flex;align-items:center;gap:.4rem}.post-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem;margin-top:.15rem}.st-draft{color:var(--cm)}.st-scheduled{color:var(--blue)}.st-published{color:var(--green)}.plat{font-size:.55rem;padding:0 .25rem;background:var(--bg3);color:var(--ll);border-radius:2px}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:95%;max-width:600px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=datetime-local],textarea,select{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:100px}.form-row{display:flex;gap:.5rem}.form-row>*{flex:1}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Pasture</span></h1><button class="btn btn-p" onclick="showNew()">+ Post</button></div>
<div class="main"><div class="overview" id="ov"></div>
<div class="toolbar"><select id="stFilter" onchange="load()"><option value="">All</option><option value="draft">Drafts</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select></div>
<div id="list"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<0)return'in '+Math.abs(Math.floor(s/60))+'m';if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function init(){const sd=await api('/api/stats');document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.draft+'</b>Drafts</div><div class="stat"><b style="color:var(--blue)">'+sd.scheduled+'</b>Scheduled</div><div class="stat"><b style="color:var(--green)">'+sd.published+'</b>Published</div>';load()}
async function load(){const st=document.getElementById('stFilter').value;const p=st?'?status='+st:'';const d=await api('/api/posts'+p);const posts=d.posts||[];
document.getElementById('list').innerHTML=posts.length?posts.map(p=>'<div class="post"><div class="post-title"><span class="st-'+p.status+'">'+p.status+'</span>'+esc(p.title)+(p.platform?'<span class="plat">'+esc(p.platform)+'</span>':'')+'</div><div class="post-meta">'+(p.scheduled_at?'<span>'+timeAgo(p.scheduled_at)+'</span>':'')+(p.tags?'<span>'+esc(p.tags)+'</span>':'')+(p.status!=='published'?'<span style="cursor:pointer;color:var(--green)" onclick="pub(\''+p.id+'\')">publish</span>':'')+'<span style="cursor:pointer;color:var(--cm)" onclick="del(\''+p.id+'\')">del</span></div></div>').join(''):'<div class="empty">No posts yet.</div>'}
async function pub(id){await api('/api/posts/'+id+'/publish',{method:'POST'});load();init()}
async function del(id){if(!confirm('Delete?'))return;await api('/api/posts/'+id,{method:'DELETE'});load();init()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Post</h2><label class="fl">Title</label><input type="text" id="np-title"><label class="fl">Content</label><textarea id="np-body" rows="5"></textarea><div class="form-row"><div><label class="fl">Platform</label><input type="text" id="np-plat" placeholder="twitter, blog, linkedin"></div><div><label class="fl">Status</label><select id="np-status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></div></div><label class="fl">Schedule For</label><input type="datetime-local" id="np-sched"><label class="fl">Tags</label><input type="text" id="np-tags"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={title:document.getElementById('np-title').value,body:document.getElementById('np-body').value,platform:document.getElementById('np-plat').value,status:document.getElementById('np-status').value,scheduled_at:document.getElementById('np-sched').value?new Date(document.getElementById('np-sched').value).toISOString():'',tags:document.getElementById('np-tags').value};if(!b.title){alert('Title required');return};await api('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load();init()}
function closeModal(){document.getElementById('modal').innerHTML=''}
init()
</script></body></html>`
